imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: en }
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    session:         ~
    trusted_proxies: ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'CmfMediaBundle:Form:fields.html.twig'
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # bundles: [ ] # if enabled, every bundle must be added
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        coffee:
           bin: %coffee.bin%
           node: %coffee.node%
           apply_to: %coffee.extension%
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

# for jackalope-doctrine-dbal
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
    orm:
        entity_managers:
            default:
                mappings:
                    ApplicationUserBundle: ~
                    SonataUserBundle: ~
                    FOSUserBundle: ~

# cmf configuration
doctrine_phpcr:
    # configure the PHPCR session
    session:
        backend: %phpcr_backend%
        workspace: %phpcr_workspace%
        username: %phpcr_user%
        password: %phpcr_pass%
    # enable the ODM layer
    odm:
        auto_generate_proxy_classes: %kernel.debug%
        locales:
            en:
                - fr
        document_managers:
            default:
                auto_mapping: false

knp_menu:
    twig: true

genemu_form:
    date:
        enabled: true
        configs:
            dateFormat: 'm/d/yy'
    select2: ~

cmf_menu:
    persistence:
        phpcr:
            menu_basepath: /cms
            content_basepath: /cms

cmf_core:
    multilang:
        locales: %locales%
    persistence:
        phpcr:
            basepath: /cms
            enabled: true

cmf_content:
    persistence:
        phpcr:
            content_basepath: /cms

cmf_routing:
    chain:
        routers_by_id:
            cmf_routing.dynamic_router: 20
            router.default: 100
    dynamic:
        enabled: true
        persistence:
            phpcr:
                admin_basepath: /cms
                route_basepaths: [/cms/home]
                content_basepath: /cms
        route_collection_limit: 10
        controllers_by_class:
            Pellr\CmsBundle\Doctrine\Phpcr\Page: cmf_content.controller:indexAction
            Symfony\Cmf\Bundle\RoutingBundle\Doctrine\Phpcr\RedirectRoute:  cmf_routing.redirect_controller:redirectAction
        templates_by_class:
            Pellr\CmsBundle\Doctrine\Phpcr\Page: base.html.twig

cmf_create:
    editor_base_path: /bundles/cmfcreate/vendor/ckeditor/

cmf_seo:
    title: CMF Sandbox - %%content_title%%
    description: The Content Management Framework. %%content_description%%
    alternate_locale: ~

fos_user:
    db_driver:      orm
    firewall_name:  main
    user_class:     Application\UserBundle\Entity\User

    group:
        group_class:   Application\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager

    service:
        user_manager: sonata.user.orm.user_manager

sonata_user:
    security_acl: false
    manager_type: orm
    class:
        user: Application\UserBundle\Entity\User
        group: Application\UserBundle\Entity\Group
    admin:
        user:
            class:          Sonata\UserBundle\Admin\Entity\UserAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle

        group:
            class:          Sonata\UserBundle\Admin\Entity\GroupAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.admin.block.search_result:
            contexts:   [admin]
        sonata_admin_doctrine_phpcr.tree_block:
            settings:
                id: '/cms'
            contexts:   [admin]
        sonata.user.block.menu:    ~
        sonata.user.block.account: ~
        sonata.block.service.text: ~
    blocks_by_class:
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\RssBlock:
            cache: cmf.block.cache.js_async

sonata_admin:
    title: %admin_brand%
    options:
        title_mode: single_text
    templates:
        layout: PellrCmsBundle:Admin:standard_layout.html.twig
    assets:
        stylesheets:
            - bundles/sonataadmin/vendor/bootstrap/dist/css/bootstrap.min.css
            - bundles/sonataadmin/vendor/AdminLTE/css/font-awesome.min.css
            - bundles/sonataadmin/vendor/AdminLTE/css/ionicons.min.css
            - bundles/sonataadmin/vendor/AdminLTE/css/AdminLTE.css

            - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css

            - bundles/sonataadmin/vendor/jqueryui/themes/base/jquery-ui.css

            - bundles/sonataadmin/vendor/select2/select2.css
            - bundles/sonataadmin/vendor/select2/select2-bootstrap.css

            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css

            - bundles/sonataadmin/css/styles.css
            - bundles/sonataadmin/css/layout.css

            - bundles/pellrcms/css/style.css
        javascripts:
            - bundles/sonataadmin/vendor/jquery/dist/jquery.min.js
            - bundles/sonataadmin/vendor/jquery.scrollTo/jquery.scrollTo.min.js
            - bundles/sonataadmin/jquery/jquery.form.js
            - bundles/sonataadmin/jquery/jquery.confirmExit.js

            - bundles/sonataadmin/vendor/jqueryui/ui/minified/jquery-ui.min.js
            - bundles/sonataadmin/vendor/jqueryui/ui/minified/i18n/jquery-ui-i18n.min.js

            - bundles/sonataadmin/vendor/bootstrap/dist/js/bootstrap.min.js
            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/js/bootstrap-editable.min.js

            - bundles/sonatacore/vendor/moment/min/moment.min.js
            - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js

            - bundles/sonataadmin/vendor/select2/select2.min.js

            - bundles/sonataadmin/App.js
            - bundles/sonataadmin/Admin.js
    extensions:
        cmf_core.admin_extension.child:
            implements:
                - Symfony\Cmf\Bundle\CoreBundle\Model\ChildInterface
        cmf_core.admin_extension.publish_workflow.time_period:
            implements:
                - Symfony\Cmf\Bundle\CoreBundle\PublishWorkflow\PublishTimePeriodInterface
        cmf_core.admin_extension.publish_workflow.publishable:
            implements:
                - Symfony\Cmf\Bundle\CoreBundle\PublishWorkflow\PublishableInterface
        cmf_core.admin_extension.translatable:
            implements:
                - Symfony\Cmf\Bundle\CoreBundle\Translatable\TranslatableInterface
        cmf_menu.admin_extension.menu_node_referrers:
            implements:
                - Symfony\Cmf\Bundle\MenuBundle\Model\MenuNodeReferrersInterface
        cmf_routing.admin_extension.route_referrers:
            implements:
                - Symfony\Cmf\Component\Routing\RouteReferrersInterface
        cmf_routing.admin_extension.frontend_link:
            implements:
                - Symfony\Cmf\Component\Routing\RouteReferrersReadInterface
            extends:
                - Symfony\Component\Routing\Route
        cmf_seo.admin_extension:
            implements:
                - Symfony\Cmf\Bundle\SeoBundle\SeoAwareInterface

    dashboard:
        blocks:
            - { position: right, type: sonata.admin.block.admin_list }
            - { position: left, type: sonata_admin_doctrine_phpcr.tree_block }
        groups:
#            content:
#                label: Content
#                items:
#                    - cmf_content.admin
#                    - cmf_block.simple_admin
#                    - cmf_block.container_admin
#                    - cmf_block.reference_admin
#                    - cmf_block.action_admin
#                    - cmf_block.imagine.slideshow_admin
#                    - cmf_block.imagine.imagine_admin
            users:
                label: Users
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group
            routing:
                label: URLs
                items:
                    - cmf_routing.route_admin
                    - cmf_routing.redirect_route_admin
            menu:
                label: Menu
                items:
                    - cmf_menu.menu_admin
                    - cmf_menu.node_admin
            cms_pages:
                label: CMS Pages
                items:
                    - pellr_cms.persistence.phpcr.admin.page

sonata_doctrine_phpcr_admin:
    document_tree_defaults: [locale]
    document_tree:
        Doctrine\ODM\PHPCR\Document\Generic:
            valid_children:
                - all
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ReferenceBlock:
            valid_children: []
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ActionBlock:
            valid_children: []
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\SimpleBlock:
            valid_children: []
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\SlideshowBlock:
            valid_children:
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ImagineBlock
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ImagineBlock:
            valid_children: []
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\RssBlock:
            valid_children: []
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ContainerBlock:
            valid_children:
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\SimpleBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ContainerBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ReferenceBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ActionBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\SlideshowBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\RssBlock
        Pellr\CmsBundle\Doctrine\Phpcr\Page:
            valid_children:
                - Pellr\CmsBundle\Doctrine\Phpcr\Page
        Symfony\Cmf\Bundle\RoutingBundle\Doctrine\Phpcr\Route:
            valid_children:
                - Symfony\Cmf\Bundle\RoutingBundle\Doctrine\Phpcr\Route
                - Symfony\Cmf\Bundle\RoutingBundle\Doctrine\Phpcr\RedirectRoute
        Symfony\Cmf\Bundle\RoutingBundle\Doctrine\Phpcr\RedirectRoute:
            valid_children: []
        Symfony\Cmf\Bundle\MenuBundle\Doctrine\Phpcr\Menu:
            valid_children:
                - Symfony\Cmf\Bundle\MenuBundle\Doctrine\Phpcr\MenuNode
        Symfony\Cmf\Bundle\MenuBundle\Doctrine\Phpcr\MenuNode:
            valid_children:
                - Symfony\Cmf\Bundle\MenuBundle\Doctrine\Phpcr\MenuNode

sonata_seo:
    page:
        title: %sonata_seo_page_title%
        metas:
            name:
                keywords: %sonata_seo_page_meta_keywords%

sensio_framework_extra:
    router:  { annotations: true }
    request: { converters: true }

liip_search:
    restrict_by_language: true;

cmf_search:
    persistence:
        phpcr:
            search_fields:
                title: title
                summary: body

# The LiipImagineBundle can be used if you want to convert on demand an image
# to a specific format. (ie a controller render the file)
# more information can be found here : https://github.com/liip/LiipImagineBundle
liip_imagine:
    filter_sets:
        # define the filter to be used with the image preview
        image_upload_thumbnail:
            data_loader: cmf_media_doctrine_phpcr
            filters:
                thumbnail: { size: [100, 100], mode: outbound }

        # default filter to be used for elfinder thumbnails
        elfinder_thumbnail:
            data_loader: cmf_media_doctrine_phpcr
            quality: 85
            filters:
                thumbnail: { size: [48, 48], mode: inset }

        cmf_block:
            data_loader: cmf_media_doctrine_phpcr
            quality: 85
            filters:
                thumbnail: { size: [50, 50], mode: outbound }

fm_elfinder:
    locale: %locale%
    editor: ckeditor
    connector:
        roots:
            media:
                driver: cmf_media.adapter.elfinder.phpcr_driver
                path: %cmf_media.persistence.phpcr.media_basepath%
                upload_allow: ['all']
                upload_max_size: 2M

doctrine_cache:
    providers:
        phpcr_meta:
            type: file_system
        phpcr_nodes:
            type: file_system

jms_serializer:
    metadata:
        auto_detection: true

fos_rest:
    view:
        force_redirects:
            html: true
        formats:
            json: true
            xml: true
        templating_formats:
            html: true
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    format_listener:
        rules:
            - { path: ^/, priorities: [ html, json, xml, css ], fallback_format: html, prefer_extension: false }
